# https://docs.digitalocean.com/glossary/app-spec
# https://docs.digitalocean.com/products/app-platform/reference/app-spec/
# The app spec, is a YAML manifest that declaratively states everything about your app.
# Including each resource and all of your app’s environment variables and configuration variables.
name: 'roblox-plus'

# The domain names where the app is accessible on the public internet.
domains:
  - domain: 'roblox.plus'
    type: 'PRIMARY'

# The region to deploy the app into.
# See also: https://docs.digitalocean.com/products/platform/availability-matrix/#app-platform-availability
region: sfo

# Get alerts when things go horribly wrong.
alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED

services:
  # This is the backend for the push notifications demo,
  # the thing actually sending the push notifications.
  - name: 'api'
    github:
      branch: 'master'
      deploy_on_push: true
      repo: 'roblox-plus/extension'
    health_check:
      http_path: '/application-metadata'
    http_port: 80
    instance_count: 1
    instance_size_slug: 'basic-xxs'
    envs:
      - key: 'ROBLOX__AUTHENTICATION__CLIENTID'
        scope: 'RUN_TIME'
        value: '2147861207470534820'

      # This should be safe to commit to source control, it's encrypted?
      # https://www.digitalocean.com/community/questions/what-are-app-spec-best-practices-for-keeping-env-secrets-secret?comment=193546
      - key: 'AUTHENTICATION_KEYS_JSON'
        scope: 'RUN_TIME'
        type: 'SECRET'
        value: 'While it should be safe to commit this value, per the above commit... I cannot, in a security-concious mind commit the encrypted value.'

      - key: 'ROBLOX__AUTHENTICATION__CLIENTSECRET'
        scope: 'RUN_TIME'
        type: 'SECRET'
        value: 'This is not in source control, for the same reason as the above secret.'
    routes:
      - path: /api
        preserve_path_prefix: true
    cors:
      allow_credentials: true
      allow_headers:
        - Content-Type
      allow_methods:
        - GET
        - POST
      allow_origins:
        - exact: http://localhost:3000
        - exact: https://localhost:3000
    source_dir: 'services/web-api'
    dockerfile_path: 'services/web-api/Dockerfile'

static_sites:
  # This is the app that the humans interact with in their web browsers.
  - name: 'app'
    github:
      branch: 'master'
      deploy_on_push: true
      repo: 'roblox-plus/extension'
    output_dir: '/app/build'
    dockerfile_path: 'services/web-app/Dockerfile'
    routes:
      - path: /
    catchall_document: index.html
